name: 品项详情
base_url: ${ENV(base_url)}
variables:
    currtime: ${make_time()}
    uuid: ${make_uuid()}
    var_access_token: ${get_accesstoken()}
#    var_access_token: 8EJAySkZS7f3AfPi3p6EHk5Tp7ezTNRA
    sign: ${make_sign($currtime, $uuid, $var_access_token)}
    productId: '3659694170161152'
    districtId: 0

request:
    headers:
        Content-Type: application/json;charset=utf-8
        User-Agent: okhttp/4.2.2
        X-MMM-AccessToken: $var_access_token
        X-MMM-AppName: com.mmm.tlmanufacture.debug
        X-MMM-AppProject: ability
        X-MMM-DeviceType: '1'
        X-MMM-Sign: $sign
        X-MMM-Timestamp: $currtime
        X-MMM-Uuid: $uuid
        X-MMM-Version: 1.10.0
    json:
        productId: $productId
        districtId: $districtId
    method: POST
    url: /v1/sale/product/detail
validate:
-   eq:
    - content.msg
    - ok

