name: 0.7.0品项列表
base_url: ${ENV(base_background_url)}
variables:
    companyId: 8
    dataType: 1
    sortType: 1
    districtPid: 0
    salesmanId:
    districtPids:
    districtId: 0


request:
    headers:
        Content-Type: application/json; charset=UTF-8
        Accept: application/json
    json:
        companyId: $companyId
        dataType: $dataType
        sortType: $sortType
        lastId: 0
        pageSize: 20
        districtPid: $districtPid
        saleRange:
        grossProfitRange:
        tagIds:
        salesmanId: $salesmanId
        districtPids: $districtPids
        districtId: $districtId
    method: POST
    url: /product-price/get-goal-product-list
validate:
-   eq:
    - content.msg
    - 请求成功
